import { ConversionCategory, Currency } from '../types';

export const conversionCategories: ConversionCategory[] = [
  {
    id: 'weight',
    name: 'Poids',
    icon: 'scale-outline',
    units: [
      { id: 'kg', name: 'Kilogramme', symbol: 'kg', toBase: 1 },
      { id: 'g', name: 'Gramme', symbol: 'g', toBase: 0.001 },
      { id: 'mg', name: 'Milligramme', symbol: 'mg', toBase: 0.000001 },
      { id: 'ton', name: 'Tonne', symbol: 't', toBase: 1000 },
      { id: 'lb', name: 'Livre', symbol: 'lb', toBase: 0.453592 },
      { id: 'oz', name: 'Once', symbol: 'oz', toBase: 0.0283495 },
      { id: 'st', name: 'Stone', symbol: 'st', toBase: 6.35029 },
    ],
  },
  {
    id: 'volume',
    name: 'Volume',
    icon: 'beaker-outline',
    units: [
      { id: 'l', name: 'Litre', symbol: 'L', toBase: 1 },
      { id: 'ml', name: 'Millilitre', symbol: 'mL', toBase: 0.001 },
      { id: 'cl', name: 'Centilitre', symbol: 'cL', toBase: 0.01 },
      { id: 'm3', name: 'Mètre cube', symbol: 'm³', toBase: 1000 },
      { id: 'dm3', name: 'Décimètre cube', symbol: 'dm³', toBase: 1 },
      { id: 'cm3', name: 'Centimètre cube', symbol: 'cm³', toBase: 0.001 },
      { id: 'gal', name: 'Gallon US', symbol: 'gal', toBase: 3.78541 },
      { id: 'qt', name: 'Quart US', symbol: 'qt', toBase: 0.946353 },
      { id: 'pt', name: 'Pinte US', symbol: 'pt', toBase: 0.473176 },
      { id: 'floz', name: 'Once liquide US', symbol: 'fl oz', toBase: 0.0295735 },
    ],
  },
  {
    id: 'area',
    name: 'Surface',
    icon: 'square-outline',
    units: [
      { id: 'm2', name: 'Mètre carré', symbol: 'm²', toBase: 1 },
      { id: 'km2', name: 'Kilomètre carré', symbol: 'km²', toBase: 1000000 },
      { id: 'cm2', name: 'Centimètre carré', symbol: 'cm²', toBase: 0.0001 },
      { id: 'mm2', name: 'Millimètre carré', symbol: 'mm²', toBase: 0.000001 },
      { id: 'ha', name: 'Hectare', symbol: 'ha', toBase: 10000 },
      { id: 'are', name: 'Are', symbol: 'a', toBase: 100 },
      { id: 'acre', name: 'Acre', symbol: 'ac', toBase: 4046.86 },
      { id: 'sqft', name: 'Pied carré', symbol: 'ft²', toBase: 0.092903 },
      { id: 'sqin', name: 'Pouce carré', symbol: 'in²', toBase: 0.00064516 },
      { id: 'sqyd', name: 'Yard carré', symbol: 'yd²', toBase: 0.836127 },
      { id: 'sqmi', name: 'Mile carré', symbol: 'mi²', toBase: 2589988.11 },
    ],
  },
  {
    id: 'length',
    name: 'Longueur',
    icon: 'resize-outline',
    units: [
      { id: 'm', name: 'Mètre', symbol: 'm', toBase: 1 },
      { id: 'km', name: 'Kilomètre', symbol: 'km', toBase: 1000 },
      { id: 'cm', name: 'Centimètre', symbol: 'cm', toBase: 0.01 },
      { id: 'mm', name: 'Millimètre', symbol: 'mm', toBase: 0.001 },
      { id: 'mi', name: 'Mile', symbol: 'mi', toBase: 1609.34 },
      { id: 'yd', name: 'Yard', symbol: 'yd', toBase: 0.9144 },
      { id: 'ft', name: 'Pied', symbol: 'ft', toBase: 0.3048 },
      { id: 'in', name: 'Pouce', symbol: 'in', toBase: 0.0254 },
      { id: 'nmi', name: 'Mile nautique', symbol: 'nmi', toBase: 1852 },
    ],
  },
];

// Taux de change approximatifs (USD comme base)
export const currencies: Currency[] = [
  { code: 'USD', name: 'Dollar américain', symbol: '$', rate: 1 },
  { code: 'EUR', name: 'Euro', symbol: '€', rate: 0.92 },
  { code: 'GBP', name: 'Livre sterling', symbol: '£', rate: 0.79 },
  { code: 'JPY', name: 'Yen japonais', symbol: '¥', rate: 149.50 },
  { code: 'CNY', name: 'Yuan chinois', symbol: '¥', rate: 7.24 },
  { code: 'INR', name: 'Roupie indienne', symbol: '₹', rate: 83.12 },
  { code: 'AUD', name: 'Dollar australien', symbol: 'A$', rate: 1.53 },
  { code: 'CAD', name: 'Dollar canadien', symbol: 'C$', rate: 1.36 },
  { code: 'CHF', name: 'Franc suisse', symbol: 'Fr', rate: 0.88 },
  { code: 'HKD', name: 'Dollar de Hong Kong', symbol: 'HK$', rate: 7.82 },
  { code: 'SGD', name: 'Dollar de Singapour', symbol: 'S$', rate: 1.34 },
  { code: 'SEK', name: 'Couronne suédoise', symbol: 'kr', rate: 10.42 },
  { code: 'KRW', name: 'Won sud-coréen', symbol: '₩', rate: 1298.50 },
  { code: 'MXN', name: 'Peso mexicain', symbol: '$', rate: 17.15 },
  { code: 'NZD', name: 'Dollar néo-zélandais', symbol: 'NZ$', rate: 1.63 },
  { code: 'NOK', name: 'Couronne norvégienne', symbol: 'kr', rate: 10.68 },
  { code: 'RUB', name: 'Rouble russe', symbol: '₽', rate: 92.50 },
  { code: 'ZAR', name: 'Rand sud-africain', symbol: 'R', rate: 18.65 },
  { code: 'TRY', name: 'Livre turque', symbol: '₺', rate: 28.95 },
  { code: 'BRL', name: 'Real brésilien', symbol: 'R$', rate: 4.97 },
  { code: 'TWD', name: 'Dollar taïwanais', symbol: 'NT$', rate: 31.45 },
  { code: 'DKK', name: 'Couronne danoise', symbol: 'kr', rate: 6.88 },
  { code: 'PLN', name: 'Zloty polonais', symbol: 'zł', rate: 4.02 },
  { code: 'THB', name: 'Baht thaïlandais', symbol: '฿', rate: 35.12 },
  { code: 'IDR', name: 'Roupie indonésienne', symbol: 'Rp', rate: 15650 },
  { code: 'HUF', name: 'Forint hongrois', symbol: 'Ft', rate: 356.25 },
  { code: 'CZK', name: 'Couronne tchèque', symbol: 'Kč', rate: 22.85 },
  { code: 'ILS', name: 'Shekel israélien', symbol: '₪', rate: 3.72 },
  { code: 'CLP', name: 'Peso chilien', symbol: '$', rate: 878.50 },
  { code: 'PHP', name: 'Peso philippin', symbol: '₱', rate: 55.85 },
  { code: 'AED', name: 'Dirham des EAU', symbol: 'د.إ', rate: 3.67 },
  { code: 'COP', name: 'Peso colombien', symbol: '$', rate: 3985 },
  { code: 'SAR', name: 'Riyal saoudien', symbol: '﷼', rate: 3.75 },
  { code: 'MYR', name: 'Ringgit malaisien', symbol: 'RM', rate: 4.72 },
  { code: 'RON', name: 'Leu roumain', symbol: 'lei', rate: 4.58 },
  { code: 'DZD', name: 'Dinar algérien', symbol: 'د.ج', rate: 134.50 },
  { code: 'TND', name: 'Dinar tunisien', symbol: 'د.ت', rate: 3.12 },
  { code: 'MAD', name: 'Dirham marocain', symbol: 'د.م.', rate: 10.05 },
  { code: 'EGP', name: 'Livre égyptienne', symbol: 'E£', rate: 30.90 },
  { code: 'PKR', name: 'Roupie pakistanaise', symbol: '₨', rate: 281.50 },
  { code: 'BDT', name: 'Taka bangladais', symbol: '৳', rate: 109.75 },
  { code: 'VND', name: 'Dong vietnamien', symbol: '₫', rate: 24350 },
  { code: 'NGN', name: 'Naira nigérian', symbol: '₦', rate: 785.50 },
  { code: 'ARS', name: 'Peso argentin', symbol: '$', rate: 365.25 },
  { code: 'UAH', name: 'Hryvnia ukrainienne', symbol: '₴', rate: 37.45 },
  { code: 'KWD', name: 'Dinar koweïtien', symbol: 'د.ك', rate: 0.31 },
  { code: 'QAR', name: 'Riyal qatari', symbol: '﷼', rate: 3.64 },
  { code: 'BHD', name: 'Dinar bahreïni', symbol: '.د.ب', rate: 0.38 },
  { code: 'OMR', name: 'Rial omanais', symbol: '﷼', rate: 0.38 },
  { code: 'JOD', name: 'Dinar jordanien', symbol: 'د.ا', rate: 0.71 },
  { code: 'LBP', name: 'Livre libanaise', symbol: 'ل.ل', rate: 89500 },
  { code: 'IQD', name: 'Dinar irakien', symbol: 'ع.د', rate: 1310 },
  { code: 'LYD', name: 'Dinar libyen', symbol: 'ل.د', rate: 4.85 },
  { code: 'SDG', name: 'Livre soudanaise', symbol: '£', rate: 601 },
  { code: 'NPR', name: 'Roupie népalaise', symbol: '₨', rate: 132.85 },
  { code: 'LKR', name: 'Roupie srilankaise', symbol: '₨', rate: 323.50 },
  { code: 'MMK', name: 'Kyat birman', symbol: 'K', rate: 2100 },
  { code: 'KZT', name: 'Tenge kazakh', symbol: '₸', rate: 456.75 },
  { code: 'UZS', name: 'Sum ouzbek', symbol: 'сўм', rate: 12250 },
  { code: 'GEL', name: 'Lari géorgien', symbol: '₾', rate: 2.68 },
  { code: 'AZN', name: 'Manat azerbaïdjanais', symbol: '₼', rate: 1.70 },
];
